source 'https://github.com/CocoaPods/Specs.git'

target 'URBNSwipeableController' do
  pod "URBNSwipeableController", :path => "../"
  target 'Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end

end
