source 'https://github.com/CocoaPods/Specs.git'

target 'URBNSwipeableController', :exclusive => true do
  pod "URBNSwipeableController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "URBNSwipeableController", :path => "../"

  pod 'FBSnapshotTestCase'
end
